# Generated by Django 4.1.5 on 2023-01-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=256)),
                ('suma', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=16)),
                ('boss', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('title', models.CharField(blank=True, max_length=16)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('adrerss', models.CharField(max_length=256)),
                ('Employee', models.ManyToManyField(blank=True, related_name='employees', to='ORTHF_app.employee')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='TypeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
            ],
        ),
        migrations.CreateModel(
            name='TypeWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begining', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORTHF_app.actions')),
                ('employee', models.ManyToManyField(to='ORTHF_app.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORTHF_app.patient')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='RealWorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_bagining', models.TimeField()),
                ('time_end', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORTHF_app.employee')),
                ('typeworking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORTHF_app.typeworking')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='type_employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ORTHF_app.typeemployee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workingtime',
            field=models.ManyToManyField(blank=True, related_name='employees', to='ORTHF_app.workingtime'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_holiday', models.IntegerField()),
                ('time_logout', models.DurationField()),
                ('time_login', models.DurationField()),
                ('holiday_typeworking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORTHF_app.typeworking')),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='employee',
            field=models.ManyToManyField(blank=True, to='ORTHF_app.typeemployee'),
        ),
    ]
